### PR TITLE
Added better exceptions when verifying the CSRF state

### PR DESCRIPTION
**Pull request by Nyholm**
This PR makes it easier to debug to find out what is wrong with the CSRF state. 

Ping @Donovan-Ensicaen

### CODE REVIEW

**Comment by Donovan-Ensicaen** [comment]
So, with this PR, I have this exception : 
```
Type: Happyr\LinkedIn\Exceptions\LinkedInApiException

Message: Could not find a stored CSRF state token.

Filename: .../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php

Line Number: 267

Backtrace:

File: .../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php
Line: 313
Function: getCode

File: .../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php
Line: 296
Function: fetchNewAccessToken

File: .../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php
Line: 216
Function: getAccessToken

File: .../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php
Line: 200
Function: getUserFromAvailableData

File: .../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php
Line: 427
Function: getUser

File:.../vendor/happyr/linkedin-api-client/src/Happyr/LinkedIn/LinkedIn.php
Line: 114
Function: getUserId

File: .../controllers/C_user.php
Line: 460
Function: isAuthenticated
```

It seems the issue comes from the storage. The storage is empty when I'm redirected on my website.

With a var_dump at the beginning of the getCode method : 

```
var_dump($storage);
--> object(Happyr\LinkedIn\Storage\SessionStorage)#42 (0) { } 
``` 

```
var_dump($this->getState());
--> NULL
```

**Comment by Nyholm** [comment]
Okey, Lets figure out why your storage is empty. 
Can you debug the `LinkedIn::establishCSRFTokenState()` function. It sets a `state` to the storage. Is it executing as expected?

Which storage are you using?

**Comment by Donovan-Ensicaen** [comment]
Ok, there is a problem with the storage. I don't use the IlluminateSessionStorage, I have a SessionStorage object.

```
 protected function establishCSRFTokenState()
    {
        if ($this->getState() === null) {
            $this->setState(md5(uniqid(mt_rand(), true)));
            $this->getStorage()->set('state', $this->getState());
        }
        var_dump($this->getState()); --> string(32) "b67da5014f79b1fbd4729f89287c8cdf" 
        var_dump($this->getStorage()); --> object(Happyr\LinkedIn\Storage\SessionStorage)#47 (0) { } 
    }
```

The storage is set but still empty.

**Comment by Nyholm** [comment]
Okey, interesting. 
Do you ever run session_start()?

https://github.com/Happyr/LinkedIn-API-client/blob/master/src/Happyr/LinkedIn/Storage/SessionStorage.php#L24

**Comment by Donovan-Ensicaen** [comment]
The session is started in the SessionStorage constructor
``` 
public function __construct()
    {
        //start the session if it not already been started
         if(php_sapi_name() !== 'cli') {
            if (session_id() === '') {
                session_start();
                echo "Session started";
            }
        }
    }

--> Session started
```
I use codeigniter but I think it couldn't create this issue. I have no issues when I don't use another redirect-uri.

**Comment by Nyholm** [comment]
So; 
```php
$urlGivesYouError = $linkedIn->getLoginUrl(array('redirect_uri' => 'http://www.mywebsite.com/index.php/C_utilisateur/storeLinkedin'));
$urlIsJustFine = $linkedIn->getLoginUrl();
```
That is really weird. That should not effect the storage at all.

Is the code where you generate the login URL on the same domain as where you would like to store the accessToken?

**Comment by Donovan-Ensicaen** [comment]
It could be a problem on the login url.

I call the login url from http://www.mywebsite.com/index.php/LoadPanel/edit_profile
When I use the method getLoginUrl() like that : 
```
$url = $linkedIn->getLoginUrl();
```
The redirect url generated is http://draafter.com/index.php/LoadPanel/edit_profile without the 'www'. In the linkedin app, I have to registered this url http://mywebsite.com/index.php/LoadPanel/edit_profile because this one doesn't work with the 'www' http://www.mywebsite.com/index.php/LoadPanel/edit_profile ...

If I use this method with the redirect-url parameter : 
```
$url = $linkedIn->getLoginUrl(array('redirect_uri' => 'http://mywebsite.com/index.php/LoadPanel/edit_profile')); 
--> it works
```
```
$url = $linkedIn->getLoginUrl(array('redirect_uri' => 'http://www.mywebsite.com/index.php/LoadPanel/edit_profile')); 
--> it doesn't work
```

If I redirect in another controller, it doesn't work
```
$url = $linkedIn->getLoginUrl(array('redirect_uri' =>'http://www.mywebsite.com/index.php/C_utilisateur/storeLinkedin'));
```
because the generated url doesn't contain the 'www'

If I use this one 
```
$url = $linkedIn->getLoginUrl(array('redirect_uri' =>'http://mywebsite.com/index.php/C_utilisateur/storeLinkedin'));
```
 IT WORKS !!

**Comment by Nyholm** [comment]
Okey. Thank you. 
The problem is that the $_SESSION is bound to a domain. www.mywebsite.com and mywebsite.com are two different domains and they do not share the $_SESSION. 

You could create an other storage (like file storage or memcache) in order to be decoupled from the issue with different domains. 

I will merge this PR because it gives more hints when debugging.

**Comment by Donovan-Ensicaen** [comment]
Yes you're right, www is like a subdomain of mywebsite.com. Thank you for your help! A better way should be to take the current url in the browser. My current url is http://www.mywebsite.com but the generated url us http://mywebsite.com.

**Comment by Nyholm** [comment]
I thought it did take the current URL.. https://github.com/Happyr/LinkedIn-API-client/blob/master/src/Happyr/LinkedIn/Http/UrlGenerator.php#L75

If there is an error here would you mind creating a PR?

**Comment by Donovan-Ensicaen** [comment]
I could be in this line 
```
$protocol = $this->getHttpProtocol() . '://www';
```
instead of
```
$protocol = $this->getHttpProtocol() . '://';
```
I'm not sure if it will fix the issue for all people or just in my case.

**Comment by Nyholm** [comment]
I think it will just cause problems if you assume that every domain will start with www.

**Comment by xmaestro** [comment]
I have a feeling this has something to do with deployment on multiple servers. i.e. You cannot use file based sessions there. You need to use memcache/redis or mysql based sessions to keep it consistent across instances.

**Pull request merged**
