### PR TITLE
Update Authenticator.php

### PR DESCRIPTION
**Pull request by mbarwick83**
Updated oAuth URL to point to LinkedIn's new oAuth User Interface.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this. This will fix #104. 

Is the old URL deprecated by LinkedIn? Can you give a link to a resource where LinkedIn informs about this change?

**Comment by mbarwick83** [comment]
Check it out here. https://developer.linkedin.com/docs/oauth2 Looks like many of the urls in the package are outdated - with current docs. It's not deprecated yet.

**Comment by Nyholm** [comment]
Great!

Would you mind updating the URL in `Authenticator::getAccessTokenFromCode` as well? (Step 3 in https://developer.linkedin.com/docs/oauth2)

Also, make sure the tests passes. 

>  Looks like many of the urls in the package are outdated - with current docs. It's not deprecated yet.

It would be awesome if you could update these as well. But that maybe another PR.

**Comment by mbarwick83** [comment]
Done. Other URLs I'll need to look at later. But looks like get/post, etc still uses the url segments you use already.

**Comment by mbarwick83** [comment]
No idea why tests are to passing. This was my first ever pull request. I updated test file, not sure what's broken but I don't have time to figure it out right now.

**Comment by Nyholm** [comment]
Thank you for your work.

**Comment by mbarwick83** [comment]
I think we might run into issues - and more stuff will need to be done. Are you able to post? Looks like I'm running into this: http://stackoverflow.com/questions/28094926/linkedin-oauth2-unable-to-verify-access-token#answer-28225463

**Comment by Nyholm** [comment]
Hm, Yes Im able to post on the wall. 

screen shot 2016-06-25 at 21 35 35
screen shot 2016-06-25 at 21 36 44

Are you sure you are using dev-master of `happyr/linkedin-api-client`?

**Pull request merged**
