### PR TITLE
Update LinkedIn.php

### PR DESCRIPTION
**Pull request by ravigehlot**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| BC breaks?      | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | MIT

#### What's in this PR?

Explain what the changes in this PR do.

#### Why?

Which problem does the PR fix? (remove this section if you linked an issue above)

#### Example Usage

``` php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)

$foo = new Foo();

// Now we can do
$foo->doSomething();
```

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

#### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. That is a weird line of comment. It should be: 

`5. If we don't have an access token (only a *code*), getAccessToken() will call fetchNewAccessToken()`

Could you update this?

**Comment by ravigehlot** [comment]
Thanks for bringing that up. Sure can! Will do.

**Comment by Nyholm** [comment]
Thank you!

**Comment by ravigehlot** [comment]
You are welcome!

**Pull request merged**
