### PR TITLE
Add full installation example to Readme.md file

### PR DESCRIPTION
**Pull request by pascalwacker**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

#### What's in this PR?

Add a full example of how to install the bundle

#### Why?

This makes it clearer for someone trying to install the bundle

#### Checklist

- [X] Updated Readme.md to describe installation

### CODE REVIEW

**Comment by Nyholm** [comment]
Awesome @pascalwacker!
You are the best!

**Comment by Nyholm** [comment]
I saw now that you made this PR on the wrong repo. It should have been to the bundle.

**Comment by pascalwacker** [comment]
@Nyholm true, I'll make a new pull request to the bundle, sorry.

**Comment by Nyholm** [comment]
No worries, I was too quick to merge. It was my fault. 

I added your PR on the bundle already. Feel free to send a new PR if you have more suggestions. 

Thank you

**Pull request merged**
